### ISSUE TITLE
Add support for Valhalla

### ISSUE THREAD

**Issue by webmap2015** [traffordDataLab/leaflet.reachability#8]
Hi, there's a isochrone API and it's pretty fast: 'https://valhalla.interline.io/isochrone?'

Could you add support for Valhalla?

Thanks.

**Comment by itsozz** [comment]
Hi, thanks for getting in touch.  At the moment the plugin is very closely coupled to the [openrouteservice isochrones API](https://openrouteservice.org/dev/#/api-docs/v2/isochrones/%7Bprofile%7D/post). In order to provide support for alternative APIs I'd have to look carefully at the inputs and outputs expected from the different services and abstract certain parts of the plugin etc.  Not saying it wouldn't be possible, but it would require a reasonable amount of change.

What do you think would be the benefits to offering support for Valhalla, and other APIs perhaps, over just using openrouteservice?

**Comment by webmap2015** [comment]
Of course, lots of plugins, especially Routing and Geocoding, support many different data providers.

**Comment by itsozz** [comment]
So the benefit is for the map developer in terms of choice, i.e. they already have an API key setup with one provider, e.g. Valhalla, and would therefore prefer to use that rather than having to create another with openrouteservice due to it being the only one supported?

My current priority is improving the accessibility of the plugin, but this is certainly something I can consider for future development.

**Comment by nilsnolde** [comment]
@itsozz I recently wrote an overview article about FOSS routing engines: https://gis-ops.com/open-source-routing-engines-and-algorithms-an-overview/ (little #shamelessplug I guess;)). In short: Valhalla is great for isochrones as well, you can add all kinds of constraints to each request, which is what most others (incl ORS) lack.

**Comment by itsozz** [comment]
Hi @nilsnolde, great to hear from you!  Thanks very much for this and the informative article - really interesting and lots to consider.

**Comment by webmap2015** [comment]
Hi, I found a sample https://www.mapzen.com/products/mobility/isochrone/

**Comment by webmap2015** [comment]
I made it.
